"""followers

Revision ID: 52572f0acf19
Revises: 56c87a19f18b
Create Date: 2018-03-25 00:07:01.141176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52572f0acf19'
down_revision = '56c87a19f18b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
